package classroom.pojo;

import java.util.Date;

public class ClassroomDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.id
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.datetime
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.building_name
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String buildingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.classRoom
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String classroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.first
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String first;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.second
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String second;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.third
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String third;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.fourth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String fourth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.fifth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String fifth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.sixth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String sixth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.seventh
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String seventh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.eighth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String eighth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.ninth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String ninth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.tenth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String tenth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.eleventh
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String eleventh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_detail.twelfth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    private String twelfth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.id
     *
     * @return the value of classroom_detail.id
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.id
     *
     * @param id the value for classroom_detail.id
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.datetime
     *
     * @return the value of classroom_detail.datetime
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.datetime
     *
     * @param datetime the value for classroom_detail.datetime
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.building_name
     *
     * @return the value of classroom_detail.building_name
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.building_name
     *
     * @param buildingName the value for classroom_detail.building_name
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.classRoom
     *
     * @return the value of classroom_detail.classRoom
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.classRoom
     *
     * @param classroom the value for classroom_detail.classRoom
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setClassroom(String classroom) {
        this.classroom = classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.first
     *
     * @return the value of classroom_detail.first
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getFirst() {
        return first;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.first
     *
     * @param first the value for classroom_detail.first
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setFirst(String first) {
        this.first = first;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.second
     *
     * @return the value of classroom_detail.second
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getSecond() {
        return second;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.second
     *
     * @param second the value for classroom_detail.second
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setSecond(String second) {
        this.second = second;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.third
     *
     * @return the value of classroom_detail.third
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getThird() {
        return third;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.third
     *
     * @param third the value for classroom_detail.third
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setThird(String third) {
        this.third = third;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.fourth
     *
     * @return the value of classroom_detail.fourth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getFourth() {
        return fourth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.fourth
     *
     * @param fourth the value for classroom_detail.fourth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setFourth(String fourth) {
        this.fourth = fourth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.fifth
     *
     * @return the value of classroom_detail.fifth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getFifth() {
        return fifth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.fifth
     *
     * @param fifth the value for classroom_detail.fifth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setFifth(String fifth) {
        this.fifth = fifth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.sixth
     *
     * @return the value of classroom_detail.sixth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getSixth() {
        return sixth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.sixth
     *
     * @param sixth the value for classroom_detail.sixth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setSixth(String sixth) {
        this.sixth = sixth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.seventh
     *
     * @return the value of classroom_detail.seventh
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getSeventh() {
        return seventh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.seventh
     *
     * @param seventh the value for classroom_detail.seventh
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setSeventh(String seventh) {
        this.seventh = seventh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.eighth
     *
     * @return the value of classroom_detail.eighth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getEighth() {
        return eighth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.eighth
     *
     * @param eighth the value for classroom_detail.eighth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setEighth(String eighth) {
        this.eighth = eighth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.ninth
     *
     * @return the value of classroom_detail.ninth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getNinth() {
        return ninth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.ninth
     *
     * @param ninth the value for classroom_detail.ninth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setNinth(String ninth) {
        this.ninth = ninth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.tenth
     *
     * @return the value of classroom_detail.tenth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getTenth() {
        return tenth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.tenth
     *
     * @param tenth the value for classroom_detail.tenth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setTenth(String tenth) {
        this.tenth = tenth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.eleventh
     *
     * @return the value of classroom_detail.eleventh
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getEleventh() {
        return eleventh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.eleventh
     *
     * @param eleventh the value for classroom_detail.eleventh
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setEleventh(String eleventh) {
        this.eleventh = eleventh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_detail.twelfth
     *
     * @return the value of classroom_detail.twelfth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getTwelfth() {
        return twelfth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_detail.twelfth
     *
     * @param twelfth the value for classroom_detail.twelfth
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setTwelfth(String twelfth) {
        this.twelfth = twelfth;
    }
}