package classroom.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ClassroomDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public ClassroomDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDatetimeIsNull() {
            addCriterion("datetime is null");
            return (Criteria) this;
        }

        public Criteria andDatetimeIsNotNull() {
            addCriterion("datetime is not null");
            return (Criteria) this;
        }

        public Criteria andDatetimeEqualTo(Date value) {
            addCriterionForJDBCDate("datetime =", value, "datetime");
            return (Criteria) this;
        }

        public Criteria andDatetimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("datetime <>", value, "datetime");
            return (Criteria) this;
        }

        public Criteria andDatetimeGreaterThan(Date value) {
            addCriterionForJDBCDate("datetime >", value, "datetime");
            return (Criteria) this;
        }

        public Criteria andDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("datetime >=", value, "datetime");
            return (Criteria) this;
        }

        public Criteria andDatetimeLessThan(Date value) {
            addCriterionForJDBCDate("datetime <", value, "datetime");
            return (Criteria) this;
        }

        public Criteria andDatetimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("datetime <=", value, "datetime");
            return (Criteria) this;
        }

        public Criteria andDatetimeIn(List<Date> values) {
            addCriterionForJDBCDate("datetime in", values, "datetime");
            return (Criteria) this;
        }

        public Criteria andDatetimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("datetime not in", values, "datetime");
            return (Criteria) this;
        }

        public Criteria andDatetimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("datetime between", value1, value2, "datetime");
            return (Criteria) this;
        }

        public Criteria andDatetimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("datetime not between", value1, value2, "datetime");
            return (Criteria) this;
        }

        public Criteria andBuildingNameIsNull() {
            addCriterion("building_name is null");
            return (Criteria) this;
        }

        public Criteria andBuildingNameIsNotNull() {
            addCriterion("building_name is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingNameEqualTo(String value) {
            addCriterion("building_name =", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameNotEqualTo(String value) {
            addCriterion("building_name <>", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameGreaterThan(String value) {
            addCriterion("building_name >", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameGreaterThanOrEqualTo(String value) {
            addCriterion("building_name >=", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameLessThan(String value) {
            addCriterion("building_name <", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameLessThanOrEqualTo(String value) {
            addCriterion("building_name <=", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameLike(String value) {
            addCriterion("building_name like", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameNotLike(String value) {
            addCriterion("building_name not like", value, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameIn(List<String> values) {
            addCriterion("building_name in", values, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameNotIn(List<String> values) {
            addCriterion("building_name not in", values, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameBetween(String value1, String value2) {
            addCriterion("building_name between", value1, value2, "buildingName");
            return (Criteria) this;
        }

        public Criteria andBuildingNameNotBetween(String value1, String value2) {
            addCriterion("building_name not between", value1, value2, "buildingName");
            return (Criteria) this;
        }

        public Criteria andClassroomIsNull() {
            addCriterion("classRoom is null");
            return (Criteria) this;
        }

        public Criteria andClassroomIsNotNull() {
            addCriterion("classRoom is not null");
            return (Criteria) this;
        }

        public Criteria andClassroomEqualTo(String value) {
            addCriterion("classRoom =", value, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomNotEqualTo(String value) {
            addCriterion("classRoom <>", value, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomGreaterThan(String value) {
            addCriterion("classRoom >", value, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomGreaterThanOrEqualTo(String value) {
            addCriterion("classRoom >=", value, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomLessThan(String value) {
            addCriterion("classRoom <", value, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomLessThanOrEqualTo(String value) {
            addCriterion("classRoom <=", value, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomLike(String value) {
            addCriterion("classRoom like", value, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomNotLike(String value) {
            addCriterion("classRoom not like", value, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomIn(List<String> values) {
            addCriterion("classRoom in", values, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomNotIn(List<String> values) {
            addCriterion("classRoom not in", values, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomBetween(String value1, String value2) {
            addCriterion("classRoom between", value1, value2, "classroom");
            return (Criteria) this;
        }

        public Criteria andClassroomNotBetween(String value1, String value2) {
            addCriterion("classRoom not between", value1, value2, "classroom");
            return (Criteria) this;
        }

        public Criteria andFirstIsNull() {
            addCriterion("first is null");
            return (Criteria) this;
        }

        public Criteria andFirstIsNotNull() {
            addCriterion("first is not null");
            return (Criteria) this;
        }

        public Criteria andFirstEqualTo(String value) {
            addCriterion("first =", value, "first");
            return (Criteria) this;
        }

        public Criteria andFirstNotEqualTo(String value) {
            addCriterion("first <>", value, "first");
            return (Criteria) this;
        }

        public Criteria andFirstGreaterThan(String value) {
            addCriterion("first >", value, "first");
            return (Criteria) this;
        }

        public Criteria andFirstGreaterThanOrEqualTo(String value) {
            addCriterion("first >=", value, "first");
            return (Criteria) this;
        }

        public Criteria andFirstLessThan(String value) {
            addCriterion("first <", value, "first");
            return (Criteria) this;
        }

        public Criteria andFirstLessThanOrEqualTo(String value) {
            addCriterion("first <=", value, "first");
            return (Criteria) this;
        }

        public Criteria andFirstLike(String value) {
            addCriterion("first like", value, "first");
            return (Criteria) this;
        }

        public Criteria andFirstNotLike(String value) {
            addCriterion("first not like", value, "first");
            return (Criteria) this;
        }

        public Criteria andFirstIn(List<String> values) {
            addCriterion("first in", values, "first");
            return (Criteria) this;
        }

        public Criteria andFirstNotIn(List<String> values) {
            addCriterion("first not in", values, "first");
            return (Criteria) this;
        }

        public Criteria andFirstBetween(String value1, String value2) {
            addCriterion("first between", value1, value2, "first");
            return (Criteria) this;
        }

        public Criteria andFirstNotBetween(String value1, String value2) {
            addCriterion("first not between", value1, value2, "first");
            return (Criteria) this;
        }

        public Criteria andSecondIsNull() {
            addCriterion("second is null");
            return (Criteria) this;
        }

        public Criteria andSecondIsNotNull() {
            addCriterion("second is not null");
            return (Criteria) this;
        }

        public Criteria andSecondEqualTo(String value) {
            addCriterion("second =", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondNotEqualTo(String value) {
            addCriterion("second <>", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondGreaterThan(String value) {
            addCriterion("second >", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondGreaterThanOrEqualTo(String value) {
            addCriterion("second >=", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondLessThan(String value) {
            addCriterion("second <", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondLessThanOrEqualTo(String value) {
            addCriterion("second <=", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondLike(String value) {
            addCriterion("second like", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondNotLike(String value) {
            addCriterion("second not like", value, "second");
            return (Criteria) this;
        }

        public Criteria andSecondIn(List<String> values) {
            addCriterion("second in", values, "second");
            return (Criteria) this;
        }

        public Criteria andSecondNotIn(List<String> values) {
            addCriterion("second not in", values, "second");
            return (Criteria) this;
        }

        public Criteria andSecondBetween(String value1, String value2) {
            addCriterion("second between", value1, value2, "second");
            return (Criteria) this;
        }

        public Criteria andSecondNotBetween(String value1, String value2) {
            addCriterion("second not between", value1, value2, "second");
            return (Criteria) this;
        }

        public Criteria andThirdIsNull() {
            addCriterion("third is null");
            return (Criteria) this;
        }

        public Criteria andThirdIsNotNull() {
            addCriterion("third is not null");
            return (Criteria) this;
        }

        public Criteria andThirdEqualTo(String value) {
            addCriterion("third =", value, "third");
            return (Criteria) this;
        }

        public Criteria andThirdNotEqualTo(String value) {
            addCriterion("third <>", value, "third");
            return (Criteria) this;
        }

        public Criteria andThirdGreaterThan(String value) {
            addCriterion("third >", value, "third");
            return (Criteria) this;
        }

        public Criteria andThirdGreaterThanOrEqualTo(String value) {
            addCriterion("third >=", value, "third");
            return (Criteria) this;
        }

        public Criteria andThirdLessThan(String value) {
            addCriterion("third <", value, "third");
            return (Criteria) this;
        }

        public Criteria andThirdLessThanOrEqualTo(String value) {
            addCriterion("third <=", value, "third");
            return (Criteria) this;
        }

        public Criteria andThirdLike(String value) {
            addCriterion("third like", value, "third");
            return (Criteria) this;
        }

        public Criteria andThirdNotLike(String value) {
            addCriterion("third not like", value, "third");
            return (Criteria) this;
        }

        public Criteria andThirdIn(List<String> values) {
            addCriterion("third in", values, "third");
            return (Criteria) this;
        }

        public Criteria andThirdNotIn(List<String> values) {
            addCriterion("third not in", values, "third");
            return (Criteria) this;
        }

        public Criteria andThirdBetween(String value1, String value2) {
            addCriterion("third between", value1, value2, "third");
            return (Criteria) this;
        }

        public Criteria andThirdNotBetween(String value1, String value2) {
            addCriterion("third not between", value1, value2, "third");
            return (Criteria) this;
        }

        public Criteria andFourthIsNull() {
            addCriterion("fourth is null");
            return (Criteria) this;
        }

        public Criteria andFourthIsNotNull() {
            addCriterion("fourth is not null");
            return (Criteria) this;
        }

        public Criteria andFourthEqualTo(String value) {
            addCriterion("fourth =", value, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthNotEqualTo(String value) {
            addCriterion("fourth <>", value, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthGreaterThan(String value) {
            addCriterion("fourth >", value, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthGreaterThanOrEqualTo(String value) {
            addCriterion("fourth >=", value, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthLessThan(String value) {
            addCriterion("fourth <", value, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthLessThanOrEqualTo(String value) {
            addCriterion("fourth <=", value, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthLike(String value) {
            addCriterion("fourth like", value, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthNotLike(String value) {
            addCriterion("fourth not like", value, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthIn(List<String> values) {
            addCriterion("fourth in", values, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthNotIn(List<String> values) {
            addCriterion("fourth not in", values, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthBetween(String value1, String value2) {
            addCriterion("fourth between", value1, value2, "fourth");
            return (Criteria) this;
        }

        public Criteria andFourthNotBetween(String value1, String value2) {
            addCriterion("fourth not between", value1, value2, "fourth");
            return (Criteria) this;
        }

        public Criteria andFifthIsNull() {
            addCriterion("fifth is null");
            return (Criteria) this;
        }

        public Criteria andFifthIsNotNull() {
            addCriterion("fifth is not null");
            return (Criteria) this;
        }

        public Criteria andFifthEqualTo(String value) {
            addCriterion("fifth =", value, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthNotEqualTo(String value) {
            addCriterion("fifth <>", value, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthGreaterThan(String value) {
            addCriterion("fifth >", value, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthGreaterThanOrEqualTo(String value) {
            addCriterion("fifth >=", value, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthLessThan(String value) {
            addCriterion("fifth <", value, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthLessThanOrEqualTo(String value) {
            addCriterion("fifth <=", value, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthLike(String value) {
            addCriterion("fifth like", value, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthNotLike(String value) {
            addCriterion("fifth not like", value, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthIn(List<String> values) {
            addCriterion("fifth in", values, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthNotIn(List<String> values) {
            addCriterion("fifth not in", values, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthBetween(String value1, String value2) {
            addCriterion("fifth between", value1, value2, "fifth");
            return (Criteria) this;
        }

        public Criteria andFifthNotBetween(String value1, String value2) {
            addCriterion("fifth not between", value1, value2, "fifth");
            return (Criteria) this;
        }

        public Criteria andSixthIsNull() {
            addCriterion("sixth is null");
            return (Criteria) this;
        }

        public Criteria andSixthIsNotNull() {
            addCriterion("sixth is not null");
            return (Criteria) this;
        }

        public Criteria andSixthEqualTo(String value) {
            addCriterion("sixth =", value, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthNotEqualTo(String value) {
            addCriterion("sixth <>", value, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthGreaterThan(String value) {
            addCriterion("sixth >", value, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthGreaterThanOrEqualTo(String value) {
            addCriterion("sixth >=", value, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthLessThan(String value) {
            addCriterion("sixth <", value, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthLessThanOrEqualTo(String value) {
            addCriterion("sixth <=", value, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthLike(String value) {
            addCriterion("sixth like", value, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthNotLike(String value) {
            addCriterion("sixth not like", value, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthIn(List<String> values) {
            addCriterion("sixth in", values, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthNotIn(List<String> values) {
            addCriterion("sixth not in", values, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthBetween(String value1, String value2) {
            addCriterion("sixth between", value1, value2, "sixth");
            return (Criteria) this;
        }

        public Criteria andSixthNotBetween(String value1, String value2) {
            addCriterion("sixth not between", value1, value2, "sixth");
            return (Criteria) this;
        }

        public Criteria andSeventhIsNull() {
            addCriterion("seventh is null");
            return (Criteria) this;
        }

        public Criteria andSeventhIsNotNull() {
            addCriterion("seventh is not null");
            return (Criteria) this;
        }

        public Criteria andSeventhEqualTo(String value) {
            addCriterion("seventh =", value, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhNotEqualTo(String value) {
            addCriterion("seventh <>", value, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhGreaterThan(String value) {
            addCriterion("seventh >", value, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhGreaterThanOrEqualTo(String value) {
            addCriterion("seventh >=", value, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhLessThan(String value) {
            addCriterion("seventh <", value, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhLessThanOrEqualTo(String value) {
            addCriterion("seventh <=", value, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhLike(String value) {
            addCriterion("seventh like", value, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhNotLike(String value) {
            addCriterion("seventh not like", value, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhIn(List<String> values) {
            addCriterion("seventh in", values, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhNotIn(List<String> values) {
            addCriterion("seventh not in", values, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhBetween(String value1, String value2) {
            addCriterion("seventh between", value1, value2, "seventh");
            return (Criteria) this;
        }

        public Criteria andSeventhNotBetween(String value1, String value2) {
            addCriterion("seventh not between", value1, value2, "seventh");
            return (Criteria) this;
        }

        public Criteria andEighthIsNull() {
            addCriterion("eighth is null");
            return (Criteria) this;
        }

        public Criteria andEighthIsNotNull() {
            addCriterion("eighth is not null");
            return (Criteria) this;
        }

        public Criteria andEighthEqualTo(String value) {
            addCriterion("eighth =", value, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthNotEqualTo(String value) {
            addCriterion("eighth <>", value, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthGreaterThan(String value) {
            addCriterion("eighth >", value, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthGreaterThanOrEqualTo(String value) {
            addCriterion("eighth >=", value, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthLessThan(String value) {
            addCriterion("eighth <", value, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthLessThanOrEqualTo(String value) {
            addCriterion("eighth <=", value, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthLike(String value) {
            addCriterion("eighth like", value, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthNotLike(String value) {
            addCriterion("eighth not like", value, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthIn(List<String> values) {
            addCriterion("eighth in", values, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthNotIn(List<String> values) {
            addCriterion("eighth not in", values, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthBetween(String value1, String value2) {
            addCriterion("eighth between", value1, value2, "eighth");
            return (Criteria) this;
        }

        public Criteria andEighthNotBetween(String value1, String value2) {
            addCriterion("eighth not between", value1, value2, "eighth");
            return (Criteria) this;
        }

        public Criteria andNinthIsNull() {
            addCriterion("ninth is null");
            return (Criteria) this;
        }

        public Criteria andNinthIsNotNull() {
            addCriterion("ninth is not null");
            return (Criteria) this;
        }

        public Criteria andNinthEqualTo(String value) {
            addCriterion("ninth =", value, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthNotEqualTo(String value) {
            addCriterion("ninth <>", value, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthGreaterThan(String value) {
            addCriterion("ninth >", value, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthGreaterThanOrEqualTo(String value) {
            addCriterion("ninth >=", value, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthLessThan(String value) {
            addCriterion("ninth <", value, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthLessThanOrEqualTo(String value) {
            addCriterion("ninth <=", value, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthLike(String value) {
            addCriterion("ninth like", value, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthNotLike(String value) {
            addCriterion("ninth not like", value, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthIn(List<String> values) {
            addCriterion("ninth in", values, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthNotIn(List<String> values) {
            addCriterion("ninth not in", values, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthBetween(String value1, String value2) {
            addCriterion("ninth between", value1, value2, "ninth");
            return (Criteria) this;
        }

        public Criteria andNinthNotBetween(String value1, String value2) {
            addCriterion("ninth not between", value1, value2, "ninth");
            return (Criteria) this;
        }

        public Criteria andTenthIsNull() {
            addCriterion("tenth is null");
            return (Criteria) this;
        }

        public Criteria andTenthIsNotNull() {
            addCriterion("tenth is not null");
            return (Criteria) this;
        }

        public Criteria andTenthEqualTo(String value) {
            addCriterion("tenth =", value, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthNotEqualTo(String value) {
            addCriterion("tenth <>", value, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthGreaterThan(String value) {
            addCriterion("tenth >", value, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthGreaterThanOrEqualTo(String value) {
            addCriterion("tenth >=", value, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthLessThan(String value) {
            addCriterion("tenth <", value, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthLessThanOrEqualTo(String value) {
            addCriterion("tenth <=", value, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthLike(String value) {
            addCriterion("tenth like", value, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthNotLike(String value) {
            addCriterion("tenth not like", value, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthIn(List<String> values) {
            addCriterion("tenth in", values, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthNotIn(List<String> values) {
            addCriterion("tenth not in", values, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthBetween(String value1, String value2) {
            addCriterion("tenth between", value1, value2, "tenth");
            return (Criteria) this;
        }

        public Criteria andTenthNotBetween(String value1, String value2) {
            addCriterion("tenth not between", value1, value2, "tenth");
            return (Criteria) this;
        }

        public Criteria andEleventhIsNull() {
            addCriterion("eleventh is null");
            return (Criteria) this;
        }

        public Criteria andEleventhIsNotNull() {
            addCriterion("eleventh is not null");
            return (Criteria) this;
        }

        public Criteria andEleventhEqualTo(String value) {
            addCriterion("eleventh =", value, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhNotEqualTo(String value) {
            addCriterion("eleventh <>", value, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhGreaterThan(String value) {
            addCriterion("eleventh >", value, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhGreaterThanOrEqualTo(String value) {
            addCriterion("eleventh >=", value, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhLessThan(String value) {
            addCriterion("eleventh <", value, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhLessThanOrEqualTo(String value) {
            addCriterion("eleventh <=", value, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhLike(String value) {
            addCriterion("eleventh like", value, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhNotLike(String value) {
            addCriterion("eleventh not like", value, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhIn(List<String> values) {
            addCriterion("eleventh in", values, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhNotIn(List<String> values) {
            addCriterion("eleventh not in", values, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhBetween(String value1, String value2) {
            addCriterion("eleventh between", value1, value2, "eleventh");
            return (Criteria) this;
        }

        public Criteria andEleventhNotBetween(String value1, String value2) {
            addCriterion("eleventh not between", value1, value2, "eleventh");
            return (Criteria) this;
        }

        public Criteria andTwelfthIsNull() {
            addCriterion("twelfth is null");
            return (Criteria) this;
        }

        public Criteria andTwelfthIsNotNull() {
            addCriterion("twelfth is not null");
            return (Criteria) this;
        }

        public Criteria andTwelfthEqualTo(String value) {
            addCriterion("twelfth =", value, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthNotEqualTo(String value) {
            addCriterion("twelfth <>", value, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthGreaterThan(String value) {
            addCriterion("twelfth >", value, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthGreaterThanOrEqualTo(String value) {
            addCriterion("twelfth >=", value, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthLessThan(String value) {
            addCriterion("twelfth <", value, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthLessThanOrEqualTo(String value) {
            addCriterion("twelfth <=", value, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthLike(String value) {
            addCriterion("twelfth like", value, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthNotLike(String value) {
            addCriterion("twelfth not like", value, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthIn(List<String> values) {
            addCriterion("twelfth in", values, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthNotIn(List<String> values) {
            addCriterion("twelfth not in", values, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthBetween(String value1, String value2) {
            addCriterion("twelfth between", value1, value2, "twelfth");
            return (Criteria) this;
        }

        public Criteria andTwelfthNotBetween(String value1, String value2) {
            addCriterion("twelfth not between", value1, value2, "twelfth");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classroom_detail
     *
     * @mbggenerated do_not_delete_during_merge Sat Jan 27 10:37:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}