package classroom.mapper;

import classroom.pojo.ClassroomDetail;
import classroom.pojo.ClassroomDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassroomDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    int countByExample(ClassroomDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    int deleteByExample(ClassroomDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    int deleteByPrimaryKey(String id);

    int deleteByYear(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    int insert(ClassroomDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    int insertSelective(ClassroomDetail record);

    int insertList(List<ClassroomDetail> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    List<ClassroomDetail> selectByExample(ClassroomDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    ClassroomDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ClassroomDetail record, @Param("example") ClassroomDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    int updateByExample(@Param("record") ClassroomDetail record, @Param("example") ClassroomDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    int updateByPrimaryKeySelective(ClassroomDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_detail
     *
     * @mbggenerated Sat Jan 27 10:37:54 CST 2018
     */
    int updateByPrimaryKey(ClassroomDetail record);
}